name: Test automation workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 13
      uses: actions/setup-java@v4
      with:
        java-version: '13'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisHeadless=true -DisLambdaTest=false

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Logs
        path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Reports
        path: report.html

    - name: Test execution status
      run: echo "Test execution completed"
